### ISSUE TITLE
WebAppStrategy without sessions

### ISSUE THREAD

**Issue by leandroz** [ibm-cloud-security/appid-serversdk-nodejs#96]
Is it possible to use WebAppStrategy without sessions?

We don't want to keep track of the sessions, we just want to issue the token, store it on localStorage and send it as `Authorization: Bareer <token>` on each request.

**Comment by motyd** [comment]
Currently there is no way to decouple App IDs webappstrategy from a session. Though you may substitute any session implementation you wish. 

If you don’t want to store the token, and want the client to send the token on each request, take a look at ApiStrategy. When you protect an endpoint with it, the middleware will look at the request instead of the session. 

This might be what you are looking for, depending on your use case.
